### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by davidgoli** [dolmen-go/openapi-preprocessor#3]
This tool looks useful, but from the current README, I'm unsure how to get started. Maybe an example of driving this tool from the command line would help? Thanks!

**Comment by dolmen** [comment]
You're very right. Even the built-in help of the binary is incorrect.

**Comment by dolmen** [comment]
And output of `openapi-preprocessor` (without args) and `openapi-preprocessor -h` differ. Very bad.

**Comment by dolmen** [comment]
I've now fixed the usage. That was step 0.

**Comment by dolmen** [comment]
@davidgoli I hope the README is now enough to get you started. I eagerly wait for your feedback.
